services:

  postgresql:
    image: postgres:16.3
    container_name: psql-server
    environment:
      POSTGRES_DB: "${PROD_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${PROD_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  postgresql-dev:
    image: postgres:16.3
    container_name: psql-server-dev
    environment:
      POSTGRES_DB: "${DEV_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${DEV_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data