services:

  postgresql:
    image: postgres:16.3
    container_name: psql-server
    environment:
      POSTGRES_DB: "${MOBILE_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${MOBILE_PORT}:5432"
    volumes:
      - $HOME/psql-data:/var/lib/postgresql/data