services:

  backend:
    image: mobile/backend:$IMAGE_BUILD
    container_name: mobile/backend
    environment:
      POSTGRES_DB: "${DATABASE_DB}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:5432"

  postgresql:
    image: postgres:16.3
    container_name: psql-server
    environment:
      POSTGRES_DB: "${DATABASE_DB}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - $HOME/psql-data:/var/lib/postgresql/data
