services:

  backend:
    image: mobile/backend:$IMAGE_BUILD
    container_name: mobile/backend
    environment:
      POSTGRES_DB: "${MOBILE_DB}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${MOBILE_PORT}:5432"